apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
spec:
  template:
    spec:
      containers:
        - name: payment-service
          env:
            - name: MAKEWAY_PAYMENT_DB_DATABASE_NAME
              valueFrom:
                secretKeyRef:
                  name: payment-db
                  key: databaseName
            - name: MAKEWAY_PAYMENT_DB_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: payment-db
                  key: endpoint
            - name: MAKEWAY_PAYMENT_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: payment-db
                  key: password
            - name: MAKEWAY_PAYMENT_DB_PORT
              valueFrom:
                secretKeyRef:
                  name: payment-db
                  key: port
            - name: MAKEWAY_PAYMENT_DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: payment-db
                  key: username
