apiVersion: apps/v1
kind: Deployment
metadata:
  name: rag-service
spec:
  template:
    spec:
      containers:
        - name: rag-service
          env:
            - name: MAKEWAY_VECTOR_STORE_DATABASE_NAME
              valueFrom:
                secretKeyRef:
                  name: vector-store
                  key: databaseName
            - name: MAKEWAY_VECTOR_STORE_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: vector-store
                  key: endpoint
            - name: MAKEWAY_VECTOR_STORE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: vector-store
                  key: password
            - name: MAKEWAY_VECTOR_STORE_PORT
              valueFrom:
                secretKeyRef:
                  name: vector-store
                  key: port
            - name: MAKEWAY_VECTOR_STORE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: vector-store
                  key: username
