# Service for the app-1-service-1 golden-path service.
apiVersion: v1
kind: Service
metadata:
  name: app-1-service-1
  labels:
    app: app-1-service-1
    managed-by: makeway
spec:
  selector:
    app: app-1-service-1
  ports:
    - name: http
      port: 80
      targetPort: 8000
      protocol: TCP