#!/usr/bin/env bash
#
# Golden-path setup for a Spring Boot service, generated by Makeway.
# Run from the service repository root (or pass the service name as $1).
#
set -euo pipefail

SERVICE_NAME="${1:-$(basename "$PWD")}"
PROJECT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

echo "[makeway][spring-boot] setting up ${SERVICE_NAME} in ${PROJECT_DIR}"

cd "${PROJECT_DIR}"

# Maven build (skiping tests keeps the golden path fast).
mvn -q -DskipTests package

echo "[makeway][spring-boot] scaffold ready. Start with: SERVICE_NAME=${SERVICE_NAME} java -jar target/makeway-spring-service-0.1.0.jar"