"""added capability_access table and made changes in database schema for others.

Revision ID: 0721e22fa3c6
Revises: 0d2d456a62f5
Create Date: 2026-08-26 16:41:02.709916

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0721e22fa3c6'
down_revision: Union[str, Sequence[str], None] = '0d2d456a62f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('capabilityaccess',
    sa.Column('createdBy', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.Column('modifiedBy', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('modifiedAt', sa.DateTime(), nullable=False),
    sa.Column('capabilityAccessId', sa.Integer(), nullable=False),
    sa.Column('capabilityId', sa.Integer(), nullable=False),
    sa.Column('serviceId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['capabilityId'], ['capability.capabilityId'], ),
    sa.ForeignKeyConstraint(['serviceId'], ['service.svcId'], ),
    sa.PrimaryKeyConstraint('capabilityAccessId')
    )
    op.create_index(op.f('ix_capabilityaccess_capabilityId'), 'capabilityaccess', ['capabilityId'], unique=False)
    op.create_index(op.f('ix_capabilityaccess_serviceId'), 'capabilityaccess', ['serviceId'], unique=False)
    # Drop every foreign key that references `environment` before the table
    # itself, otherwise Postgres refuses the DROP (DependentObjectsStillExist).
    op.drop_constraint(op.f('capability_envId_fkey'), 'capability', type_='foreignkey')
    op.drop_constraint(op.f('deploymentsetup_envId_fkey'), 'deploymentsetup', type_='foreignkey')
    op.drop_constraint(op.f('namespace_envId_fkey'), 'namespace', type_='foreignkey')
    op.drop_index(op.f('ix_environment_appId'), table_name='environment')
    op.drop_index(op.f('ix_environment_clusterId'), table_name='environment')
    op.drop_table('environment')
    op.drop_index(op.f('ix_capability_envId'), table_name='capability')
    op.drop_index(op.f('ix_capability_serviceId'), table_name='capability')
    op.drop_constraint(op.f('capability_serviceId_fkey'), 'capability', type_='foreignkey')
    op.drop_column('capability', 'serviceId')
    op.drop_column('capability', 'envId')
    op.add_column('cluster', sa.Column('environment', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.drop_index(op.f('ix_deploymentsetup_envId'), table_name='deploymentsetup')
    op.drop_constraint(op.f('uq_deployment_setup_service_env'), 'deploymentsetup', type_='unique')
    op.drop_column('deploymentsetup', 'envId')
    op.drop_index(op.f('ix_namespace_envId'), table_name='namespace')
    op.drop_constraint(op.f('uq_namespace_service_env'), 'namespace', type_='unique')
    op.create_unique_constraint('uq_namespace_service_cluster', 'namespace', ['serviceId', 'clusterId'])
    op.drop_column('namespace', 'envId')
    op.add_column('service', sa.Column('clusterId', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('uq_service_app_svc'), 'service', type_='unique')
    op.create_index(op.f('ix_service_clusterId'), 'service', ['clusterId'], unique=False)
    op.create_unique_constraint('uq_service_app_svc_cluster', 'service', ['appId', 'svcName', 'clusterId'])
    op.create_foreign_key(None, 'service', 'cluster', ['clusterId'], ['clusterId'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'service', type_='foreignkey')
    op.drop_constraint('uq_service_app_svc_cluster', 'service', type_='unique')
    op.drop_index(op.f('ix_service_clusterId'), table_name='service')
    op.create_unique_constraint(op.f('uq_service_app_svc'), 'service', ['appId', 'svcName'], postgresql_nulls_not_distinct=False)
    op.drop_column('service', 'clusterId')
    op.add_column('namespace', sa.Column('envId', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('deploymentsetup', sa.Column('envId', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('capability', sa.Column('envId', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('capability', sa.Column('serviceId', sa.INTEGER(), autoincrement=False, nullable=False))
    # Recreate `environment` before attaching the foreign keys that reference it.
    op.create_table('environment',
    sa.Column('createdBy', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('createdAt', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('modifiedBy', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('modifiedAt', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('envId', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('envName', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('clusterId', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('appId', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['appId'], ['app.appId'], name=op.f('environment_appId_fkey')),
    sa.ForeignKeyConstraint(['clusterId'], ['cluster.clusterId'], name=op.f('environment_clusterId_fkey')),
    sa.PrimaryKeyConstraint('envId', name=op.f('environment_pkey')),
    sa.UniqueConstraint('appId', 'envName', name=op.f('uq_environment_app_env'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_environment_clusterId'), 'environment', ['clusterId'], unique=False)
    op.create_index(op.f('ix_environment_appId'), 'environment', ['appId'], unique=False)
    op.drop_constraint('uq_namespace_service_cluster', 'namespace', type_='unique')
    op.create_unique_constraint(op.f('uq_namespace_service_env'), 'namespace', ['serviceId', 'envId'], postgresql_nulls_not_distinct=False)
    op.create_foreign_key(op.f('namespace_envId_fkey'), 'namespace', 'environment', ['envId'], ['envId'])
    op.create_index(op.f('ix_namespace_envId'), 'namespace', ['envId'], unique=False)
    op.create_foreign_key(op.f('deploymentsetup_envId_fkey'), 'deploymentsetup', 'environment', ['envId'], ['envId'])
    op.create_unique_constraint(op.f('uq_deployment_setup_service_env'), 'deploymentsetup', ['serviceId', 'envId'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_deploymentsetup_envId'), 'deploymentsetup', ['envId'], unique=False)
    op.drop_column('cluster', 'environment')
    op.create_foreign_key(op.f('capability_envId_fkey'), 'capability', 'environment', ['envId'], ['envId'])
    op.create_foreign_key(op.f('capability_serviceId_fkey'), 'capability', 'service', ['serviceId'], ['svcId'])
    op.create_index(op.f('ix_capability_serviceId'), 'capability', ['serviceId'], unique=False)
    op.create_index(op.f('ix_capability_envId'), 'capability', ['envId'], unique=False)
    op.drop_index(op.f('ix_capabilityaccess_serviceId'), table_name='capabilityaccess')
    op.drop_index(op.f('ix_capabilityaccess_capabilityId'), table_name='capabilityaccess')
    op.drop_table('capabilityaccess')
    # ### end Alembic commands ###
