"""renamed deployConfigRepoUrl field to gitOpsRepoUrl

Revision ID: 0d2d456a62f5
Revises: b5f1b60ab16b
Create Date: 2026-08-23 20:06:40.672406

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '0d2d456a62f5'
down_revision: Union[str, Sequence[str], None] = 'b5f1b60ab16b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('app', sa.Column('gitOpsRepoUrl', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.drop_column('app', 'deployConfigRepoUrl')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('app', sa.Column('deployConfigRepoUrl', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('app', 'gitOpsRepoUrl')
    # ### end Alembic commands ###
