"""adding cicdRepoUrl field to the app

Revision ID: 507402037b2e
Revises: 8662e308e6c9
Create Date: 2026-08-23 20:01:15.968719

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '507402037b2e'
down_revision: Union[str, Sequence[str], None] = '8662e308e6c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('app', sa.Column('appRepoUrl', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('app', sa.Column('cicdRepoUrl', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.drop_column('app', 'repoUrl')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('app', sa.Column('repoUrl', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('app', 'cicdRepoUrl')
    op.drop_column('app', 'appRepoUrl')
    # ### end Alembic commands ###
