"""migration update

Revision ID: 6a2e736707f3
Revises: a3f92c1e7b40
Create Date: 2026-09-03 00:20:01.485892

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6a2e736707f3'
down_revision: Union[str, Sequence[str], None] = 'a3f92c1e7b40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('deploymentsetup', 'argocdAppName',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('deploymentsetup', 'lastSyncedAt',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('deploymentsetup', 'errorMessage',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('deploymentsetup', 'errorMessage',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('deploymentsetup', 'lastSyncedAt',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('deploymentsetup', 'argocdAppName',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
