"""initial schema

Revision ID: 8662e308e6c9
Revises: 
Create Date: 2026-08-23 16:53:33.855491

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8662e308e6c9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cluster',
    sa.Column('createdBy', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.Column('modifiedBy', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('modifiedAt', sa.DateTime(), nullable=False),
    sa.Column('clusterId', sa.Integer(), nullable=False),
    sa.Column('clusterName', sqlmodel.sql.sqltypes.AutoString(length=63), nullable=False),
    sa.Column('kubeApiEndpoint', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('clusterId'),
    sa.UniqueConstraint('clusterName')
    )
    op.create_table('team',
    sa.Column('createdBy', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.Column('modifiedBy', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('modifiedAt', sa.DateTime(), nullable=False),
    sa.Column('teamId', sa.Integer(), nullable=False),
    sa.Column('teamName', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('teamId'),
    sa.UniqueConstraint('teamName')
    )
    op.create_table('user',
    sa.Column('createdBy', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.Column('modifiedBy', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('modifiedAt', sa.DateTime(), nullable=False),
    sa.Column('userId', sa.Uuid(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=320), nullable=False),
    sa.Column('passwordHash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('userId'),
    sa.UniqueConstraint('email')
    )
    op.create_table('app',
    sa.Column('createdBy', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.Column('modifiedBy', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('modifiedAt', sa.DateTime(), nullable=False),
    sa.Column('appId', sa.Integer(), nullable=False),
    sa.Column('appName', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('repoUrl', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('teamId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['teamId'], ['team.teamId'], ),
    sa.PrimaryKeyConstraint('appId'),
    sa.UniqueConstraint('appName')
    )
    op.create_index(op.f('ix_app_teamId'), 'app', ['teamId'], unique=False)
    op.create_table('teammember',
    sa.Column('teamMemberId', sa.Integer(), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('isDeleted', sa.Boolean(), nullable=False),
    sa.Column('teamId', sa.Integer(), nullable=False),
    sa.Column('userId', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['teamId'], ['team.teamId'], ),
    sa.ForeignKeyConstraint(['userId'], ['user.userId'], ),
    sa.PrimaryKeyConstraint('teamMemberId'),
    sa.UniqueConstraint('teamId', 'userId', name='uq_teammember_team_user')
    )
    op.create_index(op.f('ix_teammember_isDeleted'), 'teammember', ['isDeleted'], unique=False)
    op.create_index(op.f('ix_teammember_role'), 'teammember', ['role'], unique=False)
    op.create_index(op.f('ix_teammember_teamId'), 'teammember', ['teamId'], unique=False)
    op.create_index(op.f('ix_teammember_userId'), 'teammember', ['userId'], unique=False)
    op.create_table('environment',
    sa.Column('createdBy', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.Column('modifiedBy', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('modifiedAt', sa.DateTime(), nullable=False),
    sa.Column('envId', sa.Integer(), nullable=False),
    sa.Column('envName', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('clusterId', sa.Integer(), nullable=False),
    sa.Column('appId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['appId'], ['app.appId'], ),
    sa.ForeignKeyConstraint(['clusterId'], ['cluster.clusterId'], ),
    sa.PrimaryKeyConstraint('envId'),
    sa.UniqueConstraint('appId', 'envName', name='uq_environment_app_env')
    )
    op.create_index(op.f('ix_environment_appId'), 'environment', ['appId'], unique=False)
    op.create_index(op.f('ix_environment_clusterId'), 'environment', ['clusterId'], unique=False)
    op.create_table('request',
    sa.Column('createdBy', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.Column('modifiedBy', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('modifiedAt', sa.DateTime(), nullable=False),
    sa.Column('requestId', sa.Integer(), nullable=False),
    sa.Column('idempotencyKey', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('requestType', sa.Enum('CREATE_APP', 'ADD_CAPABILITY', 'DELETE_CAPABILITY', 'DELETE_APP', 'UPDATE_RESOURCE', 'UPDATE_APP', name='requesttype'), nullable=False),
    sa.Column('requestStatus', sa.Enum('PENDING', 'IN_PROGRESS', 'SUCCESS', 'FAILED', 'PARTIALLY_FAILED', name='requeststatus'), nullable=False),
    sa.Column('rawRequest', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('appId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['appId'], ['app.appId'], ),
    sa.PrimaryKeyConstraint('requestId'),
    sa.UniqueConstraint('idempotencyKey')
    )
    op.create_index(op.f('ix_request_appId'), 'request', ['appId'], unique=False)
    op.create_table('service',
    sa.Column('createdBy', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.Column('modifiedBy', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('modifiedAt', sa.DateTime(), nullable=False),
    sa.Column('svcId', sa.Integer(), nullable=False),
    sa.Column('svcName', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('serviceType', sa.Enum('SPRING_BOOT', 'FASTAPI', 'NODEJS', name='servicetype'), nullable=False),
    sa.Column('repoPath', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('appId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['appId'], ['app.appId'], ),
    sa.PrimaryKeyConstraint('svcId'),
    sa.UniqueConstraint('appId', 'svcName', name='uq_service_app_svc')
    )
    op.create_index(op.f('ix_service_appId'), 'service', ['appId'], unique=False)
    op.create_table('capability',
    sa.Column('createdBy', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.Column('modifiedBy', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('modifiedAt', sa.DateTime(), nullable=False),
    sa.Column('capabilityId', sa.Integer(), nullable=False),
    sa.Column('capabilityType', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'SUCCESS', 'FAILED', 'PARTIALLY_FAILED', name='capabilitystatus'), nullable=False),
    sa.Column('errorMessage', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('serviceId', sa.Integer(), nullable=False),
    sa.Column('envId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['envId'], ['environment.envId'], ),
    sa.ForeignKeyConstraint(['serviceId'], ['service.svcId'], ),
    sa.PrimaryKeyConstraint('capabilityId')
    )
    op.create_index(op.f('ix_capability_envId'), 'capability', ['envId'], unique=False)
    op.create_index(op.f('ix_capability_serviceId'), 'capability', ['serviceId'], unique=False)
    op.create_table('deploymentsetup',
    sa.Column('createdBy', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.Column('modifiedBy', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('modifiedAt', sa.DateTime(), nullable=False),
    sa.Column('deploymentSetupId', sa.Integer(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('argocdAppName', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('lastSyncedAt', sa.DateTime(), nullable=False),
    sa.Column('errorMessage', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('serviceId', sa.Integer(), nullable=False),
    sa.Column('envId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['envId'], ['environment.envId'], ),
    sa.ForeignKeyConstraint(['serviceId'], ['service.svcId'], ),
    sa.PrimaryKeyConstraint('deploymentSetupId'),
    sa.UniqueConstraint('serviceId', 'envId', name='uq_deployment_setup_service_env')
    )
    op.create_index(op.f('ix_deploymentsetup_envId'), 'deploymentsetup', ['envId'], unique=False)
    op.create_index(op.f('ix_deploymentsetup_serviceId'), 'deploymentsetup', ['serviceId'], unique=False)
    op.create_table('namespace',
    sa.Column('createdBy', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.Column('modifiedBy', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('modifiedAt', sa.DateTime(), nullable=False),
    sa.Column('namespaceId', sa.Integer(), nullable=False),
    sa.Column('k8sNamespaceName', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'SUCCESS', 'FAILED', name='namespacestatus'), nullable=False),
    sa.Column('serviceId', sa.Integer(), nullable=False),
    sa.Column('envId', sa.Integer(), nullable=False),
    sa.Column('clusterId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['clusterId'], ['cluster.clusterId'], ),
    sa.ForeignKeyConstraint(['envId'], ['environment.envId'], ),
    sa.ForeignKeyConstraint(['serviceId'], ['service.svcId'], ),
    sa.PrimaryKeyConstraint('namespaceId'),
    sa.UniqueConstraint('serviceId', 'envId', name='uq_namespace_service_env')
    )
    op.create_index(op.f('ix_namespace_clusterId'), 'namespace', ['clusterId'], unique=False)
    op.create_index(op.f('ix_namespace_envId'), 'namespace', ['envId'], unique=False)
    op.create_index(op.f('ix_namespace_serviceId'), 'namespace', ['serviceId'], unique=False)
    op.create_table('accessbinding',
    sa.Column('createdBy', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.Column('modifiedBy', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('modifiedAt', sa.DateTime(), nullable=False),
    sa.Column('accessBindingId', sa.Integer(), nullable=False),
    sa.Column('roleArn', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('accessType', sa.Enum('READ', 'WRITE', 'READ_WRITE', name='accessbindingstatus'), nullable=False),
    sa.Column('capabilityId', sa.Integer(), nullable=False),
    sa.Column('namespaceId', sa.Integer(), nullable=False),
    sa.Column('serviceId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['capabilityId'], ['capability.capabilityId'], ),
    sa.ForeignKeyConstraint(['namespaceId'], ['namespace.namespaceId'], ),
    sa.ForeignKeyConstraint(['serviceId'], ['service.svcId'], ),
    sa.PrimaryKeyConstraint('accessBindingId'),
    sa.UniqueConstraint('capabilityId', 'serviceId', 'namespaceId', name='uq_access_binding_cap_svc_ns')
    )
    op.create_index(op.f('ix_accessbinding_capabilityId'), 'accessbinding', ['capabilityId'], unique=False)
    op.create_index(op.f('ix_accessbinding_namespaceId'), 'accessbinding', ['namespaceId'], unique=False)
    op.create_index(op.f('ix_accessbinding_serviceId'), 'accessbinding', ['serviceId'], unique=False)
    op.create_table('infrarequirement',
    sa.Column('createdBy', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.Column('modifiedBy', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('modifiedAt', sa.DateTime(), nullable=False),
    sa.Column('infraRequirementId', sa.Integer(), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('secretRef', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('outputRef', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('errorMessage', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('capabilityId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['capabilityId'], ['capability.capabilityId'], ),
    sa.PrimaryKeyConstraint('infraRequirementId')
    )
    op.create_index(op.f('ix_infrarequirement_capabilityId'), 'infrarequirement', ['capabilityId'], unique=False)
    op.create_table('job',
    sa.Column('createdBy', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.Column('modifiedBy', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('modifiedAt', sa.DateTime(), nullable=False),
    sa.Column('jobId', sa.Integer(), nullable=False),
    sa.Column('step', sa.Enum('CREATE_PROJECT', 'PROVISION_INFRA', 'ARGOCD_SETUP', name='jobstep'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'SUCCESS', 'FAILED', name='jobstatus'), nullable=False),
    sa.Column('stepFunctionExecutionArn', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('errorDetail', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('requestId', sa.Integer(), nullable=False),
    sa.Column('capabilityId', sa.Integer(), nullable=True),
    sa.Column('deploymentSetupId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['capabilityId'], ['capability.capabilityId'], ),
    sa.ForeignKeyConstraint(['deploymentSetupId'], ['deploymentsetup.deploymentSetupId'], ),
    sa.ForeignKeyConstraint(['requestId'], ['request.requestId'], ),
    sa.PrimaryKeyConstraint('jobId')
    )
    op.create_index(op.f('ix_job_capabilityId'), 'job', ['capabilityId'], unique=False)
    op.create_index(op.f('ix_job_deploymentSetupId'), 'job', ['deploymentSetupId'], unique=False)
    op.create_index(op.f('ix_job_requestId'), 'job', ['requestId'], unique=False)
    op.create_table('networkisolationrule',
    sa.Column('createdBy', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.Column('modifiedBy', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('modifiedAt', sa.DateTime(), nullable=False),
    sa.Column('ruleId', sa.Integer(), nullable=False),
    sa.Column('ruleType', sa.Enum('K8S_NETWORK_POLICY', 'SECURITY_GROUP', name='networkisolationruletype'), nullable=False),
    sa.Column('targetRef', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('namespaceId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['namespaceId'], ['namespace.namespaceId'], ),
    sa.PrimaryKeyConstraint('ruleId')
    )
    op.create_index(op.f('ix_networkisolationrule_namespaceId'), 'networkisolationrule', ['namespaceId'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_networkisolationrule_namespaceId'), table_name='networkisolationrule')
    op.drop_table('networkisolationrule')
    op.drop_index(op.f('ix_job_requestId'), table_name='job')
    op.drop_index(op.f('ix_job_deploymentSetupId'), table_name='job')
    op.drop_index(op.f('ix_job_capabilityId'), table_name='job')
    op.drop_table('job')
    op.drop_index(op.f('ix_infrarequirement_capabilityId'), table_name='infrarequirement')
    op.drop_table('infrarequirement')
    op.drop_index(op.f('ix_accessbinding_serviceId'), table_name='accessbinding')
    op.drop_index(op.f('ix_accessbinding_namespaceId'), table_name='accessbinding')
    op.drop_index(op.f('ix_accessbinding_capabilityId'), table_name='accessbinding')
    op.drop_table('accessbinding')
    op.drop_index(op.f('ix_namespace_serviceId'), table_name='namespace')
    op.drop_index(op.f('ix_namespace_envId'), table_name='namespace')
    op.drop_index(op.f('ix_namespace_clusterId'), table_name='namespace')
    op.drop_table('namespace')
    op.drop_index(op.f('ix_deploymentsetup_serviceId'), table_name='deploymentsetup')
    op.drop_index(op.f('ix_deploymentsetup_envId'), table_name='deploymentsetup')
    op.drop_table('deploymentsetup')
    op.drop_index(op.f('ix_capability_serviceId'), table_name='capability')
    op.drop_index(op.f('ix_capability_envId'), table_name='capability')
    op.drop_table('capability')
    op.drop_index(op.f('ix_service_appId'), table_name='service')
    op.drop_table('service')
    op.drop_index(op.f('ix_request_appId'), table_name='request')
    op.drop_table('request')
    op.drop_index(op.f('ix_environment_clusterId'), table_name='environment')
    op.drop_index(op.f('ix_environment_appId'), table_name='environment')
    op.drop_table('environment')
    op.drop_index(op.f('ix_teammember_userId'), table_name='teammember')
    op.drop_index(op.f('ix_teammember_teamId'), table_name='teammember')
    op.drop_index(op.f('ix_teammember_role'), table_name='teammember')
    op.drop_index(op.f('ix_teammember_isDeleted'), table_name='teammember')
    op.drop_table('teammember')
    op.drop_index(op.f('ix_app_teamId'), table_name='app')
    op.drop_table('app')
    op.drop_table('user')
    op.drop_table('team')
    op.drop_table('cluster')
    # ### end Alembic commands ###
