"""renamed cicdRepoUrl field to the deployConfigRepoUrl

Revision ID: b5f1b60ab16b
Revises: 507402037b2e
Create Date: 2026-08-23 20:02:35.876785

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'b5f1b60ab16b'
down_revision: Union[str, Sequence[str], None] = '507402037b2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('app', sa.Column('deployConfigRepoUrl', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.drop_column('app', 'cicdRepoUrl')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('app', sa.Column('cicdRepoUrl', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('app', 'deployConfigRepoUrl')
    # ### end Alembic commands ###
