apiVersion: aws.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: makeway
spec:
  credentials:
    source: Secret
    secretRef:
      namespace: crossplane-system
      name: provider-creds
      key: creds