"use strict";

// Golden-path Node.js service scaffold, generated by Makeway.

const express = require("express");

const SERVICE_NAME = process.env.SERVICE_NAME || "__SERVICE_NAME__";
const PORT = process.env.PORT || 3000;

const app = express();
app.use(express.json());

app.get("/", (_req, res) => {
  res.json({ service: SERVICE_NAME, status: "ok" });
});

app.get("/health", (_req, res) => {
  res.json({ status: "healthy" });
});

app.listen(PORT, () => {
  console.log(`[makeway][node-js] ${SERVICE_NAME} listening on :${PORT}`);
});

module.exports = app;