#!/usr/bin/env bash
#
# Golden-path setup for a Node.js service, generated by Makeway.
# Run from the service repository root (or pass the service name as $1).
#
set -euo pipefail

SERVICE_NAME="${1:-$(basename "$PWD")}"
PROJECT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

echo "[makeway][node-js] setting up ${SERVICE_NAME} in ${PROJECT_DIR}"

cd "${PROJECT_DIR}"

npm install --no-audit --no-fund

# Smoke-check that the entrypoint starts and serves /health.
PORT=0 node -e "require('./server.js')" &
NODE_PID=$!
sleep 2
kill "${NODE_PID}" 2>/dev/null || true
wait "${NODE_PID}" 2>/dev/null || true

echo "[makeway][node-js] scaffold ready. Start with: SERVICE_NAME=${SERVICE_NAME} npm start"