# Service for the test-service-6 golden-path service.
apiVersion: v1
kind: Service
metadata:
  name: test-service-6
  labels:
    app: test-service-6
    managed-by: makeway
spec:
  selector:
    app: test-service-6
  ports:
    - name: http
      port: 80
      targetPort: 8000
      protocol: TCP